										-- Practice Query - 1

-- SELECT

SELECT *
FROM COUNTRIES;

SELECT *
FROM DEPARTMENTS;

SELECT FIRST_NAME , LAST_NAME
FROM EMPLOYEES;

-- WHERE

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 OR SALARY > 8000;

-- ARITHMATIC OPERATOR

SELECT FIRST_NAME,SALARY,SALARY+10000
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

-- COMPARISON OPERATOR

SELECT *
FROM EMPLOYEES
WHERE SALARY >= 6000;

-- LOGICAL AND OR OPERATOR

SELECT *
FROM EMPLOYEES
-- WHERE DEPARTMENT_ID = 60 OR SALARY > 8000;
WHERE DEPARTMENT_ID = 70 AND SALARY >= 9000;

-- DISTINCT

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

-- ORDER BY

SELECT *
FROM EMPLOYEES
-- ORDER BY SALARY ASC; 
ORDER BY SALARY DESC;

-- LIMIT 

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC -- ASC;
-- LIMIT 5;
LIMIT 4,5;

-- OFFSET

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC -- ASC;
LIMIT 5
OFFSET 4;

-- LIKE 

SELECT *
FROM EMPLOYEES
-- WHERE LAST_NAME LIKE 'GREEN%'
WHERE LAST_NAME LIKE '%EE%';

-- AS

SELECT FIRST_NAME AS NAME ,SALARY AS 'CURRENT SALARY' , SALARY + 10000 AS 'INCREASED SALARY'
FROM EMPLOYEES;


------------------------------------------------------------------------------------------------------------------------------------
										-- Functions - 2
                                        
SELECT FIRST_NAME , UPPER(FIRST_NAME)
FROM EMPLOYEES;

SELECT FIRST_NAME , LOWER(FIRST_NAME)
FROM EMPLOYEES;

SELECT COS(RADIANS(90));
SELECT COS(0);
SELECT ACOS(1);

SELECT PI();

SELECT ROUND(12.567,2);
SELECT ROUND(12.564,2);

SELECT RAND();

------------------------------------------------------------------------------------------------------------------------------------
									-- Group Functions - 3
 
SELECT MAX(SALARY)
FROM EMPLOYEES;

SELECT MIN(SALARY)
FROM EMPLOYEES;

SELECT AVG(SALARY)
FROM EMPLOYEES;

SELECT COUNT(SALARY)
FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID)
FROM EMPLOYEES;

SELECT COUNT(*)
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES;

------------------------------------------------------------------------------------------------------------------------------------
										-- GROUP BY, HAVING - 4

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID !=20
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) > 5000;

SELECT DEPARTMENT_ID, AVG(SALARY) AS SAL
FROM EMPLOYEES
WHERE DEPARTMENT_ID !=20
GROUP BY DEPARTMENT_ID
HAVING SAL > 5000;

------------------------------------------------------------------------------------------------------------------------------------
											-- ALTER TABLE - 5
     
-- ADD

ALTER TABLE EMPLOYEES
ADD COLUMN ADDRESS VARCHAR(50);

-- DROP

ALTER TABLE EMPLOYEES
DROP COLUMN adress ;

-- MODIFY

ALTER TABLE EMPLOYEES
ADD COLUMN MODIFY_COL DECIMAL;

ALTER TABLE EMPLOYEES
-- MODIFY COLUMN MODIFY_COL VARCHAR(50);
MODIFY COLUMN MODIFY_COL VARCHAR(70);

SELECT *
FROM EMPLOYEES;
